### ISSUE TITLE
Unknown item type 'annotation'

### ISSUE THREAD

**Issue by volker-fr** [dhondta/zotero-cli#12]
Running into an issue downloading the attachments. Seems like annotations aren't supported yet.

```
zotero-cli --verbose
23:36:16 [DEBUG] Getting collections from cache '/home/user/.zotero/cache/collections.json'...
23:36:16 [DEBUG] Getting items from cache '/home/user/.zotero/cache/items.json'...
23:36:16 [DEBUG] Getting attachments from zotero.org...
^TTraceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 117, in __init__
    with cached_file.open() as f:
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 1548, in open
    return io.open(
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 1383, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 646, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.zotero/cache/attachments.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 889, in <module>
    z = ZoteroCLI(args.id, ["user", "group"][args.group or GROUP_FILE.exists()], args.key)
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 145, in __init__
    raise ValueError("Unknown item type '%s'" % c['data']['itemType'])
ValueError: Unknown item type 'annotation'
```

**Comment by dhondta** [comment]
Hi @volker-fr !
Thank you for reporting this.
Can you please test with `pip3 install --upgrade https://github.com/dhondta/zotero-cli` and tell me if it works ?

**Comment by volker-fr** [comment]
The specific issue is resolved. I will create a separate PR for a new bug. Thanks for the fix :)
