### ISSUE TITLE
Failure saving results on setup/reset

### ISSUE THREAD

**Issue by volker-fr** [dhondta/zotero-cli#14]
```
% ls $HOME/.zotero/cache 
collections.json  items.json

% zotero-cli -v           
18:13:31 [DEBUG] Getting collections from zotero.org...
18:13:31 [DEBUG] Saving collections to cache '/home/user/.zotero/cache/collections.json'...
18:13:31 [DEBUG] Getting items from zotero.org...
18:14:17 [DEBUG] Saving items to cache '/home/user/.zotero/cache/items.json'...
18:14:18 [DEBUG] Getting attachments from zotero.org...
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 114, in __init__
    with cached_file.open() as f:
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 1548, in open
    return io.open(
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 1383, in _opener
    return self._accessor.open(self, flags, mode)
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pathlib2/__init__.py", line 646, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.zotero/cache/attachments.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 888, in <module>
    z = ZoteroCLI(args.id, ["user", "group"][args.group or GROUP_FILE.exists()], args.key)
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 135, in __init__
    if i['meta']['numChildren'] > 0:
KeyError: 'numChildren'
```

Creating the file as empty json works

```
% echo "{}" > $HOME/.zotero/cache/attachments.json 
% echo "{}" > $HOME/.zotero/cache/notes.json 
% echo "{}" > $HOME/.zotero/cache/annotations.json 

zotero-cli -v                                     
18:28:37 [DEBUG] Getting collections from cache '/home/user/.zotero/cache/collections.json'...
18:28:37 [DEBUG] Getting items from cache '/home/user/.zotero/cache/items.json'...
18:28:37 [DEBUG] Getting attachments from cache '/home/user/.zotero/cache/attachments.json'...
18:28:37 [DEBUG] Getting notes from cache '/home/user/.zotero/cache/notes.json'...
18:28:37 [DEBUG] Getting annotations from cache '/home/user/.zotero/cache/annotations.json'...
18:28:37 [DEBUG] Opening marks from cache '/home/user/.zotero/cache/marks.json'...
```

Of course then the cache files are empty, and `zotero-cli reset` will delete the files and start from scratch again.

**Comment by dhondta** [comment]
Hi @volker-fr !
Thank you for reporting this one too. :-)
Can you please test with `pip3 install --upgrade https://github.com/dhondta/zotero-cli` and tell me if it works ?

**Comment by volker-fr** [comment]
Yes, this fixed it. Thanks.

Side note, the command you share doesn't work for me. But this one does:

```
pip3 install --upgrade git+https://github.com/dhondta/zotero-cli.git
```
