### ISSUE TITLE
Example code leads to errors

### ISSUE THREAD

**Issue by volker-fr** [dhondta/zotero-cli#15]
Not a blocker for me. In the README, there is the following example code:

```
zotero-cli show year title itemType numPages --filter "collections:biblio" --filter "title:detect" --limit ">date:10"
```

Looks like it has some issues handling the data it has. I get for pages errors if the page is as not an integer.
```
19:28:30 [WARNING] Bad pages value 'S20'
```

Dates also fail a lot with the following error:
```
19:34:24 [WARNING] Bad datetime format: January 1, 2021 for item titled 'XXXX'. Using default date 1900-01-01.
```
Different time formats that throw errors:
```
July 1, 2021
2021/11
2021/07/05
2019-07-20T05:00:01
```

More errors
```
% zotero-cli show - --query "top-50-most-relevants"
19:28:30 [WARNING] Bad pages value '...'
19:42:12 [WARNING] Bad datetime format: .... for item titled '...'. Using default date 1900-01-01.
... a lot more warnings as the above two ...
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 905, in <module>
    z.show(args.field, args.filter, args.sort, args.desc, args.limit)
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tinyscript/preimports/log.py", line 99, in _wrapper
    return f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/site-packages/tinyscript/helpers/decorators.py", line 112, in wrapper
    return f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 705, in show
    headers, data = self._items(fields, filters, sort, desc, limit)
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 484, in _items
    dt = set(ZoteroCLI.date(i['data']['date']).timestamp() for i in items.values()) - {dt_zero}
  File "/home/user/.pyenv/versions/3.10.6/bin/zotero-cli", line 484, in <genexpr>
    dt = set(ZoteroCLI.date(i['data']['date']).timestamp() for i in items.values()) - {dt_zero}
KeyError: 'date'
```

**Comment by dhondta** [comment]
Fixed with b80f10c1f790e527e979b37108e0d368e58a0cfc
